export interface TranscriptSegment {
    id: string;
    text: string;
    timestamp: number;
    isQuestion: boolean;
    confidence: number;
    isFinal: boolean;
}

export interface Question {
    id: string;
    text: string;
    timestamp: number;
    answer?: string;
    answerSources?: string[];
    isAnswered: boolean;
}

export interface Note {
    id: string;
    content: string;
    timestamp: number;
    lectureId: string;
    isAutoGenerated: boolean;
    tags: string[];
}

export interface Material {
    id: string;
    name: string;
    type: "pdf" | "ppt" | "image" | "screenshot";
    path: string;
    lectureId: string;
    uploadedAt: Date;
    extractedText?: string;
    thumbnailUrl?: string;
}

export interface Lecture {
    id: string;
    title: string;
    subjectId: string;
    startedAt: Date;
    endedAt?: Date;
    duration?: number;
    isActive: boolean;
    transcript: TranscriptSegment[];
    questions: Question[];
    notes: Note[];
    materials: Material[];
    summary?: string;
}

export interface Subject {
    id: string;
    name: string;
    semesterId: string;
    color: string;
    icon: string;
    lectures: Lecture[];
}

export interface Semester {
    id: string;
    name: string;
    year: number;
    isActive: boolean;
    subjects: Subject[];
}

export interface RecordingState {
    isRecording: boolean;
    isPaused: boolean;
    duration: number;
    audioLevel: number;
}

export const mockSemesters: Semester[] = [
    {
        id: "sem-1",
        name: "Semester 6",
        year: 2024,
        isActive: true,
        subjects: [
            {
                id: "sub-1",
                name: "Machine Learning",
                semesterId: "sem-1",
                color: "#14b8a6",
                icon: "brain",
                lectures: [
                    {
                        id: "lec-1",
                        title: "Introduction to Neural Networks",
                        subjectId: "sub-1",
                        startedAt: new Date("2024-01-15T10:00:00"),
                        endedAt: new Date("2024-01-15T11:30:00"),
                        duration: 90,
                        isActive: false,
                        transcript: [],
                        questions: [],
                        notes: [],
                        materials: [],
                        summary: "Covered basics of neural networks including perceptrons, activation functions, and forward propagation."
                    },
                    {
                        id: "lec-2",
                        title: "Backpropagation Deep Dive",
                        subjectId: "sub-1",
                        startedAt: new Date("2024-01-17T10:00:00"),
                        isActive: true,
                        transcript: [],
                        questions: [],
                        notes: [],
                        materials: []
                    }
                ]
            },
            {
                id: "sub-2",
                name: "Database Systems",
                semesterId: "sem-1",
                color: "#f59e0b",
                icon: "database",
                lectures: []
            },
            {
                id: "sub-3",
                name: "Computer Networks",
                semesterId: "sem-1",
                color: "#8b5cf6",
                icon: "network",
                lectures: []
            }
        ]
    }
];

export const mockTranscript: TranscriptSegment[] = [
    {
        id: "t-1",
        text: "Today we're going to discuss neural networks and their applications in modern machine learning.",
        timestamp: 0,
        isQuestion: false,
        confidence: 0.95,
        isFinal: true
    },
    {
        id: "t-2",
        text: "Neural networks are inspired by the biological neural networks in our brains.",
        timestamp: 12,
        isQuestion: false,
        confidence: 0.92,
        isFinal: true
    },
    {
        id: "t-3",
        text: "Can anyone tell me what is the basic unit of a neural network?",
        timestamp: 28,
        isQuestion: true,
        confidence: 0.98,
        isFinal: true
    },
    {
        id: "t-4",
        text: "The basic unit is called a neuron or perceptron.",
        timestamp: 45,
        isQuestion: false,
        confidence: 0.94,
        isFinal: true
    }
];
