"use client";

import { useState } from "react";
import { useLectureStore } from "@/store/lecture-store";
import { Button } from "@/components/ui/button";
import { Textarea } from "@/components/ui/textarea";
import {
    PlusIcon,
    SaveIcon,
    SparklesIcon,
    TrashIcon,
    BookOpenIcon,
    ClockIcon,
    TagIcon
} from "lucide-react";
import { cn } from "@/lib/utils";

export function NotesPanel() {
    const { notes, addNote, updateNote, deleteNote, getCurrentLecture, recording } = useLectureStore();
    const [isEditing, setIsEditing] = useState(false);
    const [editContent, setEditContent] = useState("");
    const [editingId, setEditingId] = useState<string | null>(null);

    const lecture = getCurrentLecture();

    const handleAddNote = () => {
        setIsEditing(true);
        setEditContent("");
        setEditingId(null);
    };

    const handleSaveNote = () => {
        if (!editContent.trim() || !lecture) return;

        if (editingId) {
            updateNote(editingId, editContent);
        } else {
            addNote({
                id: `note-${Date.now()}`,
                content: editContent,
                timestamp: recording.duration,
                lectureId: lecture.id,
                isAutoGenerated: false,
                tags: []
            });
        }

        setIsEditing(false);
        setEditContent("");
        setEditingId(null);
    };

    const handleEditNote = (note: typeof notes[0]) => {
        setIsEditing(true);
        setEditContent(note.content);
        setEditingId(note.id);
    };

    const handleDeleteNote = (id: string) => {
        deleteNote(id);
        if (editingId === id) {
            setIsEditing(false);
            setEditContent("");
            setEditingId(null);
        }
    };

    const formatTimestamp = (seconds: number): string => {
        const m = Math.floor(seconds / 60);
        const s = seconds % 60;
        return `${m}:${s.toString().padStart(2, "0")}`;
    };

    return (
        <div className="flex flex-col h-full">
            <div className="flex items-center justify-between p-4 border-b border-border">
                <div className="flex items-center gap-2">
                    <BookOpenIcon className="size-5" />
                    <h2 className="font-semibold">Notes</h2>
                    <span className="text-xs text-muted-foreground bg-muted px-2 py-0.5 rounded-full">
                        {notes.length}
                    </span>
                </div>
                <div className="flex items-center gap-2">
                    <Button variant="outline" size="sm" className="gap-1.5">
                        <SparklesIcon className="size-3" />
                        <span className="hidden sm:inline">Auto-Generate</span>
                    </Button>
                    <Button onClick={handleAddNote} size="sm" className="gap-1.5">
                        <PlusIcon className="size-3" />
                        <span className="hidden sm:inline">Add Note</span>
                    </Button>
                </div>
            </div>

            <div className="flex-1 overflow-y-auto p-4 space-y-3">
                {isEditing && (
                    <div className="rounded-xl border border-primary/50 bg-primary/5 p-3 space-y-3">
                        <Textarea
                            placeholder="Write your note here..."
                            value={editContent}
                            onChange={(e) => setEditContent(e.target.value)}
                            className="min-h-[100px] resize-none border-0 bg-transparent p-0 focus-visible:ring-0"
                            autoFocus
                        />
                        <div className="flex items-center justify-between">
                            <div className="flex items-center gap-2 text-xs text-muted-foreground">
                                <ClockIcon className="size-3" />
                                <span>at {formatTimestamp(recording.duration)}</span>
                            </div>
                            <div className="flex items-center gap-2">
                                <Button
                                    variant="ghost"
                                    size="sm"
                                    onClick={() => {
                                        setIsEditing(false);
                                        setEditContent("");
                                        setEditingId(null);
                                    }}
                                >
                                    Cancel
                                </Button>
                                <Button
                                    size="sm"
                                    onClick={handleSaveNote}
                                    disabled={!editContent.trim()}
                                    className="gap-1.5"
                                >
                                    <SaveIcon className="size-3" />
                                    Save
                                </Button>
                            </div>
                        </div>
                    </div>
                )}

                {notes.length === 0 && !isEditing ? (
                    <div className="flex flex-col items-center justify-center py-12 text-center">
                        <div className="size-12 rounded-full bg-muted flex items-center justify-center mb-3">
                            <BookOpenIcon className="size-6 text-muted-foreground" />
                        </div>
                        <p className="text-sm text-muted-foreground">
                            No notes yet. Add notes manually or let AI generate them.
                        </p>
                    </div>
                ) : (
                    notes.map((note) => (
                        <div
                            key={note.id}
                            className={cn(
                                "group rounded-xl border border-border p-3 space-y-2 hover:border-primary/30 transition-colors",
                                note.isAutoGenerated && "bg-muted/30"
                            )}
                        >
                            <div className="flex items-start justify-between gap-2">
                                <p className="text-sm leading-relaxed flex-1">{note.content}</p>
                                <div className="flex items-center gap-1 opacity-0 group-hover:opacity-100 transition-opacity">
                                    <Button
                                        variant="ghost"
                                        size="icon-sm"
                                        className="size-6"
                                        onClick={() => handleEditNote(note)}
                                    >
                                        <SaveIcon className="size-3" />
                                    </Button>
                                    <Button
                                        variant="ghost"
                                        size="icon-sm"
                                        className="size-6 text-destructive hover:text-destructive"
                                        onClick={() => handleDeleteNote(note.id)}
                                    >
                                        <TrashIcon className="size-3" />
                                    </Button>
                                </div>
                            </div>
                            <div className="flex items-center gap-3 text-xs text-muted-foreground">
                                <span className="flex items-center gap-1">
                                    <ClockIcon className="size-3" />
                                    {formatTimestamp(note.timestamp)}
                                </span>
                                {note.isAutoGenerated && (
                                    <span className="flex items-center gap-1 text-primary">
                                        <SparklesIcon className="size-3" />
                                        AI Generated
                                    </span>
                                )}
                                {note.tags.length > 0 && (
                                    <span className="flex items-center gap-1">
                                        <TagIcon className="size-3" />
                                        {note.tags.join(", ")}
                                    </span>
                                )}
                            </div>
                        </div>
                    ))
                )}
            </div>
        </div>
    );
}
