"use client";

import { useState } from "react";
import { useLectureStore } from "@/store/lecture-store";
import { Button } from "@/components/ui/button";
import { Textarea } from "@/components/ui/textarea";
import { toast } from "sonner";
import {
    PlusIcon,
    SparklesIcon,
    TrashIcon,
    ClockIcon,
    TagIcon,
    PencilIcon,
    CheckIcon,
    XIcon,
    Loader2Icon
} from "lucide-react";
import { cn } from "@/lib/utils";

const API_URL = process.env.NEXT_PUBLIC_API_URL || "http://localhost:8000";

export function NotesPanel() {
    const { notes, addNote, updateNote, deleteNote, getCurrentLecture, recording, transcript } = useLectureStore();
    const [isEditing, setIsEditing] = useState(false);
    const [editContent, setEditContent] = useState("");
    const [editingId, setEditingId] = useState<string | null>(null);
    const [isSummarizing, setIsSummarizing] = useState(false);

    const lecture = getCurrentLecture();

    const handleAddNote = () => {
        setIsEditing(true);
        setEditContent("");
        setEditingId(null);
    };

    const handleSaveNote = () => {
        if (!editContent.trim() || !lecture) return;

        if (editingId) {
            updateNote(editingId, editContent);
        } else {
            addNote({
                id: `note-${Date.now()}`,
                content: editContent,
                timestamp: recording.duration,
                lectureId: lecture.id,
                isAutoGenerated: false,
                tags: []
            });
        }

        setIsEditing(false);
        setEditContent("");
        setEditingId(null);
    };

    const handleEditNote = (note: typeof notes[0]) => {
        setIsEditing(true);
        setEditContent(note.content);
        setEditingId(note.id);
    };

    const handleDeleteNote = (id: string) => {
        deleteNote(id);
        if (editingId === id) {
            setIsEditing(false);
            setEditContent("");
            setEditingId(null);
        }
    };

    const handleAutoSummarize = async () => {
        if (transcript.length === 0) {
            toast.error("No transcript content to summarize");
            return;
        }

        if (!lecture) {
            toast.error("No lecture selected");
            return;
        }

        setIsSummarizing(true);
        toast.loading("Generating summary...", { id: "summarize" });

        try {
            const transcriptText = transcript
                .filter(s => s.isFinal)
                .map(s => s.text)
                .join(" ");

            // Use dedicated summary generation endpoint
            const response = await fetch(`${API_URL}/api/summary/generate`, {
                method: "POST",
                headers: { "Content-Type": "application/json" },
                body: JSON.stringify({
                    content: transcriptText.slice(0, 3000),
                    style: "bullet"
                })
            });

            const data = await response.json();
            const summary = data.summary || data.answer || "Could not generate summary.";

            // Add as auto-generated note
            addNote({
                id: `note-${Date.now()}`,
                content: summary,
                timestamp: recording.duration,
                lectureId: lecture.id,
                isAutoGenerated: true,
                tags: ["AI Summary"]
            });

            toast.success("Summary generated!", { id: "summarize" });
        } catch (error) {
            console.error("Summarize error:", error);
            toast.error("Failed to generate summary", { id: "summarize" });
        } finally {
            setIsSummarizing(false);
        }
    };

    const formatTimestamp = (seconds: number): string => {
        const m = Math.floor(seconds / 60);
        const s = seconds % 60;
        return `${m}:${s.toString().padStart(2, "0")}`;
    };

    return (
        <div className="flex flex-col h-full space-y-6">
            <div className="flex items-center justify-between pb-2 border-b border-border/40">
                <div className="flex items-center gap-2">
                    <span className="text-sm font-medium text-muted-foreground">{notes.length} notes taken</span>
                </div>
                <div className="flex items-center gap-2">
                    <Button
                        variant="ghost"
                        size="sm"
                        className="gap-1.5 text-primary hover:text-primary hover:bg-primary/10"
                        onClick={handleAutoSummarize}
                        disabled={isSummarizing}
                    >
                        {isSummarizing ? (
                            <Loader2Icon className="size-3.5 animate-spin" />
                        ) : (
                            <SparklesIcon className="size-3.5" />
                        )}
                        <span className="hidden sm:inline">Auto-Summarize</span>
                    </Button>
                    <Button onClick={handleAddNote} size="sm" variant="secondary" className="gap-1.5 rounded-full px-4">
                        <PlusIcon className="size-3.5" />
                        <span className="hidden sm:inline">New Note</span>
                    </Button>
                </div>
            </div>

            <div className="space-y-6 pb-20">
                {isEditing && (
                    <div className="rounded-2xl border border-primary/20 bg-primary/5 p-4 space-y-4 shadow-sm">
                        <div className="flex items-center gap-2 text-xs text-primary font-medium">
                            <ClockIcon className="size-3" />
                            <span>Timestamp: {formatTimestamp(recording.duration)}</span>
                        </div>
                        <Textarea
                            placeholder="Jot down your thoughts..."
                            value={editContent}
                            onChange={(e) => setEditContent(e.target.value)}
                            className="min-h-[120px] resize-none border-0 bg-transparent p-0 text-base placeholder:text-muted-foreground/50 focus-visible:ring-0 leading-relaxed"
                            autoFocus
                        />
                        <div className="flex items-center justify-end gap-2 pt-2">
                            <Button
                                variant="ghost"
                                size="sm"
                                onClick={() => {
                                    setIsEditing(false);
                                    setEditContent("");
                                    setEditingId(null);
                                }}
                                className="h-8 rounded-full"
                            >
                                <XIcon className="mr-1 size-3" />
                                Cancel
                            </Button>
                            <Button
                                size="sm"
                                onClick={handleSaveNote}
                                disabled={!editContent.trim()}
                                className="h-8 rounded-full px-4"
                            >
                                <CheckIcon className="mr-1 size-3" />
                                Save Note
                            </Button>
                        </div>
                    </div>
                )}

                {notes.length === 0 && !isEditing ? (
                    <div className="flex flex-col items-center justify-center py-16 text-center opacity-60">
                        <div className="size-16 rounded-full bg-secondary flex items-center justify-center mb-4">
                            <PlusIcon className="size-6 text-muted-foreground" />
                        </div>
                        <p className="text-base font-medium">No notes yet</p>
                        <p className="text-sm text-muted-foreground mt-1">
                            Click "New Note" to start writing.
                        </p>
                    </div>
                ) : (
                    notes.map((note) => (
                        <div
                            key={note.id}
                            className={cn(
                                "group relative p-4 rounded-2xl transition-all hover:bg-secondary/30",
                                note.isAutoGenerated && "bg-secondary/10"
                            )}
                        >
                            <div className="absolute right-4 top-4 opacity-0 group-hover:opacity-100 transition-opacity flex gap-1">
                                <Button
                                    variant="ghost"
                                    size="icon-sm"
                                    className="size-8 rounded-full hover:bg-background shadow-sm"
                                    onClick={() => handleEditNote(note)}
                                >
                                    <PencilIcon className="size-3.5 text-muted-foreground" />
                                </Button>
                                <Button
                                    variant="ghost"
                                    size="icon-sm"
                                    className="size-8 rounded-full hover:bg-background shadow-sm hover:text-destructive"
                                    onClick={() => handleDeleteNote(note.id)}
                                >
                                    <TrashIcon className="size-3.5 text-muted-foreground" />
                                </Button>
                            </div>

                            <div className="flex items-center gap-2 mb-2">
                                <span className="font-mono text-xs text-muted-foreground bg-secondary/50 px-2 py-0.5 rounded-md">
                                    {formatTimestamp(note.timestamp)}
                                </span>
                                {note.isAutoGenerated && (
                                    <span className="flex items-center gap-1 text-[10px] text-primary font-medium uppercase tracking-wider">
                                        <SparklesIcon className="size-3" />
                                        AI Generated
                                    </span>
                                )}
                            </div>

                            <p className="text-base leading-relaxed text-foreground/90 whitespace-pre-wrap">
                                {note.content}
                            </p>

                            {note.tags.length > 0 && (
                                <div className="flex flex-wrap gap-2 mt-3">
                                    {note.tags.map(tag => (
                                        <span key={tag} className="text-xs flex items-center gap-1 text-muted-foreground">
                                            <TagIcon className="size-3" />
                                            {tag}
                                        </span>
                                    ))}
                                </div>
                            )}
                        </div>
                    ))
                )}
            </div>
        </div>
    );
}
