export interface TranscriptSegment {
    id: string;
    text: string;
    timestamp: number;
    isQuestion: boolean;
    confidence: number;
    isFinal: boolean;
}

export interface Question {
    id: string;
    text: string;
    timestamp: number;
    answer?: string;
    answerSources?: string[];
    isAnswered: boolean;
}

export interface Note {
    id: string;
    content: string;
    timestamp: number;
    lectureId: string;
    isAutoGenerated: boolean;
    tags: string[];
}

export interface Material {
    id: string;
    name: string;
    type: "pdf" | "ppt" | "image" | "screenshot";
    path: string;
    lectureId: string;
    uploadedAt: Date;
    extractedText?: string;
    thumbnailUrl?: string;
}

export interface Lecture {
    id: string;
    title: string;
    subjectId: string;
    startedAt: Date;
    endedAt?: Date;
    duration?: number;
    isActive: boolean;
    transcript: TranscriptSegment[];
    questions: Question[];
    notes: Note[];
    materials: Material[];
    summary?: string;
}

export interface Subject {
    id: string;
    name: string;
    semesterId: string;
    color: string;
    icon: string;
    lectures: Lecture[];
}

export interface Semester {
    id: string;
    name: string;
    year: number;
    isActive: boolean;
    subjects: Subject[];
}

export interface RecordingState {
    isRecording: boolean;
    isPaused: boolean;
    duration: number;
    audioLevel: number;
}

// Colors for subjects
export const SUBJECT_COLORS = [
    "#14b8a6", // teal
    "#f59e0b", // amber
    "#8b5cf6", // violet
    "#ec4899", // pink
    "#3b82f6", // blue
    "#10b981", // emerald
    "#f97316", // orange
    "#6366f1", // indigo
];

// Get random color for new subject
export function getRandomColor(): string {
    return SUBJECT_COLORS[Math.floor(Math.random() * SUBJECT_COLORS.length)];
}

// Generate unique ID
export function generateId(prefix: string = "id"): string {
    return `${prefix}-${Date.now()}-${Math.random().toString(36).substr(2, 9)}`;
}
